"""empty message

Revision ID: 4a024cdbc579
Revises: 
Create Date: 2024-01-11 14:25:32.263994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a024cdbc579'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stockdata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('SECURITY_CODE', sa.String(length=50), nullable=True),
    sa.Column('SECURITY_NAME_ABBR', sa.String(length=50), nullable=True),
    sa.Column('INCOME_datajson', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('SECURITY_CODE')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stockdata')
    # ### end Alembic commands ###
