"""empty message

Revision ID: 878fb815e9d3
Revises: 4a024cdbc579
Create Date: 2024-01-11 14:26:23.663064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '878fb815e9d3'
down_revision = '4a024cdbc579'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stockdataprocess',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('SECURITY_CODE', sa.String(length=50), nullable=True),
    sa.Column('SECURITY_NAME_ABBR', sa.String(length=50), nullable=True),
    sa.Column('PRICE_dataprocess', sa.JSON(), nullable=True),
    sa.Column('INCOME_dataprocess', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('SECURITY_CODE')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stockdataprocess')
    # ### end Alembic commands ###
