"""empty message

Revision ID: ba7d2d5e407f
Revises: 878fb815e9d3
Create Date: 2024-01-11 15:49:58.771674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba7d2d5e407f'
down_revision = '878fb815e9d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stockdata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('PRICE_datajson', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stockdata', schema=None) as batch_op:
        batch_op.drop_column('PRICE_datajson')

    # ### end Alembic commands ###
